// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: pkg/agent/api/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw data to be signed (e.g. a git commit object).
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Optional: A specific key ID to use for signing. If empty, the agent
	// will use its default identity.
	KeyId         string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_pkg_agent_api_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SignRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type SignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full COSE Sign1 signature envelope.
	Signature     []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_pkg_agent_api_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the key (e.g., SHA256 fingerprint of the public key).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A human-readable comment for the identity (e.g., key file path or hardware token name).
	Comment       string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_pkg_agent_api_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ListIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*Identity            `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentitiesResponse) Reset() {
	*x = ListIdentitiesResponse{}
	mi := &file_pkg_agent_api_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentitiesResponse) ProtoMessage() {}

func (x *ListIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ListIdentitiesResponse) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

var File_pkg_agent_api_v1_agent_proto protoreflect.FileDescriptor

const file_pkg_agent_api_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/agent/api/v1/agent.proto\x12\x0fsignet.agent.v1\x1a\x1bgoogle/protobuf/empty.proto\"8\n" +
	"\vSignRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\",\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"4\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"S\n" +
	"\x16ListIdentitiesResponse\x129\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x19.signet.agent.v1.IdentityR\n" +
	"identities2\xa5\x01\n" +
	"\vSignetAgent\x12C\n" +
	"\x04Sign\x12\x1c.signet.agent.v1.SignRequest\x1a\x1d.signet.agent.v1.SignResponse\x12Q\n" +
	"\x0eListIdentities\x12\x16.google.protobuf.Empty\x1a'.signet.agent.v1.ListIdentitiesResponseB5Z3github.com/agentic-research/signet/pkg/agent/api/v1b\x06proto3"

var (
	file_pkg_agent_api_v1_agent_proto_rawDescOnce sync.Once
	file_pkg_agent_api_v1_agent_proto_rawDescData []byte
)

func file_pkg_agent_api_v1_agent_proto_rawDescGZIP() []byte {
	file_pkg_agent_api_v1_agent_proto_rawDescOnce.Do(func() {
		file_pkg_agent_api_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_api_v1_agent_proto_rawDesc), len(file_pkg_agent_api_v1_agent_proto_rawDesc)))
	})
	return file_pkg_agent_api_v1_agent_proto_rawDescData
}

var file_pkg_agent_api_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_agent_api_v1_agent_proto_goTypes = []any{
	(*SignRequest)(nil),            // 0: signet.agent.v1.SignRequest
	(*SignResponse)(nil),           // 1: signet.agent.v1.SignResponse
	(*Identity)(nil),               // 2: signet.agent.v1.Identity
	(*ListIdentitiesResponse)(nil), // 3: signet.agent.v1.ListIdentitiesResponse
	(*emptypb.Empty)(nil),          // 4: google.protobuf.Empty
}
var file_pkg_agent_api_v1_agent_proto_depIdxs = []int32{
	2, // 0: signet.agent.v1.ListIdentitiesResponse.identities:type_name -> signet.agent.v1.Identity
	0, // 1: signet.agent.v1.SignetAgent.Sign:input_type -> signet.agent.v1.SignRequest
	4, // 2: signet.agent.v1.SignetAgent.ListIdentities:input_type -> google.protobuf.Empty
	1, // 3: signet.agent.v1.SignetAgent.Sign:output_type -> signet.agent.v1.SignResponse
	3, // 4: signet.agent.v1.SignetAgent.ListIdentities:output_type -> signet.agent.v1.ListIdentitiesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_agent_api_v1_agent_proto_init() }
func file_pkg_agent_api_v1_agent_proto_init() {
	if File_pkg_agent_api_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_api_v1_agent_proto_rawDesc), len(file_pkg_agent_api_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_api_v1_agent_proto_goTypes,
		DependencyIndexes: file_pkg_agent_api_v1_agent_proto_depIdxs,
		MessageInfos:      file_pkg_agent_api_v1_agent_proto_msgTypes,
	}.Build()
	File_pkg_agent_api_v1_agent_proto = out.File
	file_pkg_agent_api_v1_agent_proto_goTypes = nil
	file_pkg_agent_api_v1_agent_proto_depIdxs = nil
}
