// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: pkg/agent/api/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignetAgent_Sign_FullMethodName           = "/signet.agent.v1.SignetAgent/Sign"
	SignetAgent_ListIdentities_FullMethodName = "/signet.agent.v1.SignetAgent/ListIdentities"
)

// SignetAgentClient is the client API for SignetAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SignetAgent is the service that runs in the background to provide
// signing and identity management.
type SignetAgentClient interface {
	// Sign uses an available identity to sign the given data, returning
	// a full Signet signature. This is the primary function of the agent.
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	// ListIdentities returns all the identities (keys) the agent can currently use.
	ListIdentities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListIdentitiesResponse, error)
}

type signetAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSignetAgentClient(cc grpc.ClientConnInterface) SignetAgentClient {
	return &signetAgentClient{cc}
}

func (c *signetAgentClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, SignetAgent_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signetAgentClient) ListIdentities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentitiesResponse)
	err := c.cc.Invoke(ctx, SignetAgent_ListIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignetAgentServer is the server API for SignetAgent service.
// All implementations must embed UnimplementedSignetAgentServer
// for forward compatibility.
//
// SignetAgent is the service that runs in the background to provide
// signing and identity management.
type SignetAgentServer interface {
	// Sign uses an available identity to sign the given data, returning
	// a full Signet signature. This is the primary function of the agent.
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	// ListIdentities returns all the identities (keys) the agent can currently use.
	ListIdentities(context.Context, *emptypb.Empty) (*ListIdentitiesResponse, error)
	mustEmbedUnimplementedSignetAgentServer()
}

// UnimplementedSignetAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignetAgentServer struct{}

func (UnimplementedSignetAgentServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedSignetAgentServer) ListIdentities(context.Context, *emptypb.Empty) (*ListIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentities not implemented")
}
func (UnimplementedSignetAgentServer) mustEmbedUnimplementedSignetAgentServer() {}
func (UnimplementedSignetAgentServer) testEmbeddedByValue()                     {}

// UnsafeSignetAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignetAgentServer will
// result in compilation errors.
type UnsafeSignetAgentServer interface {
	mustEmbedUnimplementedSignetAgentServer()
}

func RegisterSignetAgentServer(s grpc.ServiceRegistrar, srv SignetAgentServer) {
	// If the following call panics, it indicates UnimplementedSignetAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignetAgent_ServiceDesc, srv)
}

func _SignetAgent_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignetAgentServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignetAgent_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignetAgentServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignetAgent_ListIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignetAgentServer).ListIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignetAgent_ListIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignetAgentServer).ListIdentities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SignetAgent_ServiceDesc is the grpc.ServiceDesc for SignetAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignetAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signet.agent.v1.SignetAgent",
	HandlerType: (*SignetAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _SignetAgent_Sign_Handler,
		},
		{
			MethodName: "ListIdentities",
			Handler:    _SignetAgent_ListIdentities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/api/v1/agent.proto",
}
