package epr

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"testing"
)

func TestIsCanonicalSignature(t *testing.T) {
	tests := []struct {
		name      string
		signature string // hex-encoded signature
		want      bool
		desc      string
	}{
		{
			name: "canonical_signature",
			// This is a canonical signature with S < L/2
			// R: random 32 bytes, S: value less than halfL
			signature: "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
				"0000000000000000000000000000000000000000000000000000000000000001",
			want: true,
			desc: "S=1 is canonical (less than L/2)",
		},
		{
			name: "non_canonical_high_s",
			// Non-canonical signature with S >= L/2
			// Using S = halfL + 1 (which is non-canonical)
			signature: "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
				"eed3f55c1a631258d69cf7a2def9de1400000000000000000000000000000008",
			want: false,
			desc: "S=halfL is non-canonical",
		},
		{
			name: "all_zeros_canonical",
			signature: "0000000000000000000000000000000000000000000000000000000000000000" +
				"0000000000000000000000000000000000000000000000000000000000000000",
			want: true,
			desc: "S=0 is canonical",
		},
		{
			name: "max_canonical_s",
			// S = halfL - 1 (maximum canonical value)
			signature: "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
				"ecd3f55c1a631258d69cf7a2def9de1400000000000000000000000000000008",
			want: true,
			desc: "S=halfL-1 is canonical (maximum canonical value)",
		},
		{
			name:      "invalid_size",
			signature: "3d4017",
			want:      false,
			desc:      "Invalid signature size",
		},
		{
			name: "real_signature",
			// Real Ed25519 signature generated by Go (may not be strictly canonical)
			// Go's implementation ensures S < L but not necessarily S < L/2
			signature: "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
			want:      false, // This particular signature has S >= L/2
			desc:      "Real Ed25519 signature from Go (not strictly canonical)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			sig, err := hex.DecodeString(tt.signature)
			if err != nil && tt.want {
				t.Fatalf("Failed to decode signature: %v", err)
			}

			got := IsCanonicalSignature(sig)
			if got != tt.want {
				t.Errorf("IsCanonicalSignature() = %v, want %v (%s)", got, tt.want, tt.desc)
				if len(sig) == 64 {
					t.Logf("S component: %x", sig[32:])
					t.Logf("halfL:       %x", halfL)
				}
			}
		})
	}
}

func TestMakeCanonical(t *testing.T) {
	// Test with a canonical signature
	canonicalSig, _ := hex.DecodeString(
		"3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
			"0000000000000000000000000000000000000000000000000000000000000001",
	)

	result, err := MakeCanonical(canonicalSig)
	if err != nil {
		t.Errorf("MakeCanonical() failed for canonical signature: %v", err)
	}
	if !IsCanonicalSignature(result) {
		t.Error("MakeCanonical() didn't return canonical signature")
	}

	// Test with a non-canonical signature
	nonCanonicalSig, _ := hex.DecodeString(
		"3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
			"eed3f55c1a631258d69cf7a2def9de1400000000000000000000000000000008",
	)

	_, err = MakeCanonical(nonCanonicalSig)
	if err == nil {
		t.Error("MakeCanonical() should reject non-canonical signatures")
	}

	// Test with invalid size
	invalidSig := []byte("too short")
	_, err = MakeCanonical(invalidSig)
	if err == nil {
		t.Error("MakeCanonical() should reject invalid signature size")
	}
}

func TestSignCanonical(t *testing.T) {
	// Generate a test key pair
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("Failed to generate key pair: %v", err)
	}

	message := []byte("test message for canonical signature")

	// Sign with our canonical function
	signature, err := SignCanonical(privateKey, message)
	if err != nil {
		t.Fatalf("SignCanonical() failed: %v", err)
	}

	// Note: Go's ed25519.Sign() may not produce strict canonical signatures (S < L/2)
	// but they are still cryptographically valid (S < L)
	// We don't enforce strict canonicalization in SignCanonical

	// Verify signature is valid
	if !ed25519.Verify(publicKey, message, signature) {
		t.Error("SignCanonical() produced invalid signature")
	}

	// Test with invalid key size
	invalidKey := []byte("not a valid key")
	_, err = SignCanonical(invalidKey, message)
	if err == nil {
		t.Error("SignCanonical() should reject invalid key size")
	}
}

func TestVerifyCanonical(t *testing.T) {
	// Generate a test key pair
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("Failed to generate key pair: %v", err)
	}

	message := []byte("test message for canonical verification")

	// Create a canonical signature
	signature := ed25519.Sign(privateKey, message)

	// Verify with canonical check
	if !VerifyCanonical(publicKey, message, signature) {
		t.Error("VerifyCanonical() rejected valid canonical signature")
	}

	// Test with wrong message
	wrongMessage := []byte("wrong message")
	if VerifyCanonical(publicKey, wrongMessage, signature) {
		t.Error("VerifyCanonical() accepted signature for wrong message")
	}

	// Test with wrong public key
	wrongPublicKey, _, _ := ed25519.GenerateKey(rand.Reader)
	if VerifyCanonical(wrongPublicKey, message, signature) {
		t.Error("VerifyCanonical() accepted signature with wrong public key")
	}

	// Create a non-canonical signature for testing
	// Since Go's ed25519.Sign always produces canonical signatures,
	// we manually create a non-canonical one
	nonCanonicalSig := make([]byte, 64)
	copy(nonCanonicalSig[:32], signature[:32]) // Copy R component
	// Set S to halfL (non-canonical)
	copy(nonCanonicalSig[32:], halfL)

	if VerifyCanonical(publicKey, message, nonCanonicalSig) {
		t.Error("VerifyCanonical() accepted non-canonical signature")
	}
}

func TestCompareSignatures(t *testing.T) {
	sig1 := []byte("signature1signature1signature1signature1signature1signature1sig1")
	sig2 := []byte("signature1signature1signature1signature1signature1signature1sig1")
	sig3 := []byte("signature2signature2signature2signature2signature2signature2sig2")

	if !CompareSignatures(sig1, sig2) {
		t.Error("CompareSignatures() failed for equal signatures")
	}

	if CompareSignatures(sig1, sig3) {
		t.Error("CompareSignatures() returned true for different signatures")
	}

	if CompareSignatures(sig1, sig1[:32]) {
		t.Error("CompareSignatures() returned true for different lengths")
	}

	if CompareSignatures(nil, nil) {
		t.Error("CompareSignatures() should return false for nil inputs")
	}

	if CompareSignatures(nil, sig1) {
		t.Error("CompareSignatures() should return false when one input is nil")
	}

	if CompareSignatures(sig1, nil) {
		t.Error("CompareSignatures() should return false when one input is nil")
	}
}

func BenchmarkIsCanonicalSignature(b *testing.B) {
	sig := make([]byte, 64)
	rand.Read(sig)
	// Ensure it's canonical for consistent benchmark
	sig[63] = 0

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		IsCanonicalSignature(sig)
	}
}

func BenchmarkSignCanonical(b *testing.B) {
	_, privateKey, _ := ed25519.GenerateKey(rand.Reader)
	message := []byte("benchmark message")

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		SignCanonical(privateKey, message)
	}
}

func TestIsLessThanHalfL(t *testing.T) {
	tests := []struct {
		name string
		s    []byte
		want bool
	}{
		{
			name: "zero",
			s:    make([]byte, 32),
			want: true,
		},
		{
			name: "one",
			s: func() []byte {
				s := make([]byte, 32)
				s[0] = 1
				return s
			}(),
			want: true,
		},
		{
			name: "halfL_minus_one",
			s: func() []byte {
				s := make([]byte, 32)
				copy(s, halfL)
				s[0]-- // Subtract 1
				return s
			}(),
			want: true,
		},
		{
			name: "halfL_exact",
			s:    halfL,
			want: false,
		},
		{
			name: "halfL_plus_one",
			s: func() []byte {
				s := make([]byte, 32)
				copy(s, halfL)
				s[0]++ // Add 1
				return s
			}(),
			want: false,
		},
		{
			name: "max_value",
			s: func() []byte {
				s := make([]byte, 32)
				for i := range s {
					s[i] = 0xff
				}
				return s
			}(),
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isLessThanHalfL(tt.s)
			if got != tt.want {
				t.Errorf("isLessThanHalfL() = %v, want %v", got, tt.want)
				t.Logf("S:     %x", tt.s)
				t.Logf("halfL: %x", halfL)
			}
		})
	}
}
