package epr

import (
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
	"testing"
)

func TestIsCanonicalSignature(t *testing.T) {
	tests := []struct {
		name      string
		signature string // hex-encoded signature
		want      bool
		desc      string
	}{
		{
			name: "canonical_signature",
			// This is a canonical signature with S < L/2
			// R: random 32 bytes, S: value less than halfL
			signature: "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
				"0000000000000000000000000000000000000000000000000000000000000001",
			want: true,
			desc: "S=1 is canonical (less than L/2)",
		},
		{
			name: "non_canonical_high_s",
			// Non-canonical signature with S >= L/2
			// Using S = halfL + 1 (which is non-canonical)
			signature: "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
				"eed3f55c1a631258d69cf7a2def9de1400000000000000000000000000000008",
			want: false,
			desc: "S=halfL is non-canonical",
		},
		{
			name: "all_zeros_canonical",
			signature: "0000000000000000000000000000000000000000000000000000000000000000" +
				"0000000000000000000000000000000000000000000000000000000000000000",
			want: true,
			desc: "S=0 is canonical",
		},
		{
			name: "max_canonical_s",
			// S = halfL - 1 (maximum canonical value)
			signature: "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
				"ecd3f55c1a631258d69cf7a2def9de1400000000000000000000000000000008",
			want: true,
			desc: "S=halfL-1 is canonical (maximum canonical value)",
		},
		{
			name:      "invalid_size",
			signature: "3d4017",
			want:      false,
			desc:      "Invalid signature size",
		},
		{
			name: "real_signature",
			// Real Ed25519 signature generated by Go (may not be strictly canonical)
			// Go's implementation ensures S < L but not necessarily S < L/2
			signature: "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
			want:      false, // This particular signature has S >= L/2
			desc:      "Real Ed25519 signature from Go (not strictly canonical)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			sig, err := hex.DecodeString(tt.signature)
			if err != nil && tt.want {
				t.Fatalf("Failed to decode signature: %v", err)
			}

			got := IsCanonicalSignature(sig)
			if got != tt.want {
				t.Errorf("IsCanonicalSignature() = %v, want %v (%s)", got, tt.want, tt.desc)
				if len(sig) == 64 {
					t.Logf("S component: %x", sig[32:])
					t.Logf("halfL:       %x", halfL)
				}
			}
		})
	}
}

func TestMakeCanonical(t *testing.T) {
	// Test with a canonical signature
	canonicalSig, _ := hex.DecodeString(
		"3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
			"0000000000000000000000000000000000000000000000000000000000000001",
	)

	result, err := MakeCanonical(canonicalSig)
	if err != nil {
		t.Errorf("MakeCanonical() failed for canonical signature: %v", err)
	}
	if !IsCanonicalSignature(result) {
		t.Error("MakeCanonical() didn't return canonical signature")
	}

	// Test with a non-canonical signature
	nonCanonicalSig, _ := hex.DecodeString(
		"3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c" +
			"eed3f55c1a631258d69cf7a2def9de1400000000000000000000000000000008",
	)

	_, err = MakeCanonical(nonCanonicalSig)
	if err == nil {
		t.Error("MakeCanonical() should reject non-canonical signatures")
	}

	// Test with invalid size
	invalidSig := []byte("too short")
	_, err = MakeCanonical(invalidSig)
	if err == nil {
		t.Error("MakeCanonical() should reject invalid signature size")
	}
}

func TestSign(t *testing.T) {
	// Generate a test key pair
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("Failed to generate key pair: %v", err)
	}

	message := []byte("test message for standard signature")

	// Sign with our standard function
	signature, err := Sign(privateKey, message)
	if err != nil {
		t.Fatalf("Sign() failed: %v", err)
	}

	// Verify signature is valid
	if !ed25519.Verify(publicKey, message, signature) {
		t.Error("Sign() produced invalid signature")
	}

	// Note: Standard signatures may or may not be canonical
	t.Logf("Signature is canonical: %v", IsCanonicalSignature(signature))

	// Test with invalid key size
	invalidKey := []byte("not a valid key")
	_, err = Sign(invalidKey, message)
	if err == nil {
		t.Error("Sign() should reject invalid key size")
	}
}

func TestTrySignCanonical(t *testing.T) {
	// Generate a test key pair
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("Failed to generate key pair: %v", err)
	}

	message := []byte("test message for canonical signature")

	// Try to sign with canonical function
	// This may fail ~50% of the time due to non-canonical signatures
	signature, err := TrySignCanonical(privateKey, message)

	if err != nil {
		// Expected failure when signature is non-canonical
		if !strings.Contains(err.Error(), "non-canonical") {
			t.Fatalf("Unexpected error from TrySignCanonical: %v", err)
		}
		t.Log("TrySignCanonical correctly rejected non-canonical signature")
		return
	}

	// If we got a signature, it must be canonical
	if !IsCanonicalSignature(signature) {
		t.Error("TrySignCanonical() returned non-canonical signature")
	}

	// And it must be valid
	if !ed25519.Verify(publicKey, message, signature) {
		t.Error("TrySignCanonical() produced invalid signature")
	}

	// And it must pass VerifyCanonical
	if !VerifyCanonical(publicKey, message, signature) {
		t.Error("TrySignCanonical() signature failed VerifyCanonical")
	}

	// Test with invalid key size
	invalidKey := []byte("not a valid key")
	_, err = TrySignCanonical(invalidKey, message)
	if err == nil {
		t.Error("TrySignCanonical() should reject invalid key size")
	}
}

func TestSignatureDeterminism(t *testing.T) {
	// Test that Ed25519 signatures are deterministic and our functions
	// behave consistently with this property

	_, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("Failed to generate key pair: %v", err)
	}

	message := []byte("determinism test message")

	// Test 1: Sign() is deterministic
	sig1, err1 := Sign(privateKey, message)
	if err1 != nil {
		t.Fatalf("Sign() failed: %v", err1)
	}

	sig2, err2 := Sign(privateKey, message)
	if err2 != nil {
		t.Fatalf("Sign() failed: %v", err2)
	}

	if !bytes.Equal(sig1, sig2) {
		t.Error("Sign() is not deterministic - produced different signatures for same input")
	}

	// Test 2: TrySignCanonical() is deterministic
	trySig1, tryErr1 := TrySignCanonical(privateKey, message)
	trySig2, tryErr2 := TrySignCanonical(privateKey, message)

	// Both calls should have the same result (both succeed or both fail)
	if (tryErr1 == nil) != (tryErr2 == nil) {
		t.Error("TrySignCanonical() is not deterministic - different error results")
	}

	if tryErr1 == nil && tryErr2 == nil {
		if !bytes.Equal(trySig1, trySig2) {
			t.Error("TrySignCanonical() is not deterministic - produced different signatures")
		}
	}

	// Test 3: Sign() and TrySignCanonical() consistency
	// If TrySignCanonical succeeds, it should produce the same signature as Sign()
	standardSig, _ := Sign(privateKey, message)
	canonicalSig, canonicalErr := TrySignCanonical(privateKey, message)

	if canonicalErr == nil {
		// TrySignCanonical succeeded, should match Sign()
		if !bytes.Equal(standardSig, canonicalSig) {
			t.Error("When TrySignCanonical succeeds, it should produce the same signature as Sign()")
		}

		// And the signature should be canonical
		if !IsCanonicalSignature(standardSig) {
			t.Error("When TrySignCanonical succeeds, Sign() should also produce a canonical signature")
		}
	} else {
		// TrySignCanonical failed, Sign() should produce non-canonical signature
		if IsCanonicalSignature(standardSig) {
			t.Error("When TrySignCanonical fails, Sign() should produce a non-canonical signature")
		}
	}

	// Test 4: Multiple attempts don't change the outcome
	for i := 0; i < 10; i++ {
		retrySignature, retryErr := TrySignCanonical(privateKey, message)

		if (retryErr == nil) != (canonicalErr == nil) {
			t.Errorf("Iteration %d: TrySignCanonical() gave different error result", i)
		}

		if retryErr == nil && canonicalErr == nil {
			if !bytes.Equal(retrySignature, canonicalSig) {
				t.Errorf("Iteration %d: TrySignCanonical() gave different signature", i)
			}
		}
	}
}

func TestSignVsTrySignCanonicalConsistency(t *testing.T) {
	// Test consistency between Sign() and TrySignCanonical() across multiple key pairs
	// This ensures our functions correctly reflect Ed25519's deterministic nature

	for i := 0; i < 20; i++ {
		publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
		if err != nil {
			t.Fatalf("Failed to generate key pair: %v", err)
		}

		message := []byte(fmt.Sprintf("test message %d", i))

		// Get signatures from both functions
		standardSig, standardErr := Sign(privateKey, message)
		canonicalSig, canonicalErr := TrySignCanonical(privateKey, message)

		if standardErr != nil {
			t.Errorf("Test %d: Sign() should never fail: %v", i, standardErr)
			continue
		}

		isCanonical := IsCanonicalSignature(standardSig)

		if isCanonical {
			// If Sign() produced a canonical signature, TrySignCanonical should succeed
			if canonicalErr != nil {
				t.Errorf("Test %d: TrySignCanonical should succeed when Sign() produces canonical signature", i)
			} else if !bytes.Equal(standardSig, canonicalSig) {
				t.Errorf("Test %d: Sign() and TrySignCanonical() should produce identical canonical signatures", i)
			}
		} else {
			// If Sign() produced a non-canonical signature, TrySignCanonical should fail
			if canonicalErr == nil {
				t.Errorf("Test %d: TrySignCanonical should fail when Sign() produces non-canonical signature", i)
			}
		}

		// Verify both signatures (if they exist) are valid
		if !ed25519.Verify(publicKey, message, standardSig) {
			t.Errorf("Test %d: Sign() produced invalid signature", i)
		}

		if canonicalErr == nil && !ed25519.Verify(publicKey, message, canonicalSig) {
			t.Errorf("Test %d: TrySignCanonical() produced invalid signature", i)
		}
	}
}

func TestVerifyCanonical(t *testing.T) {
	// Generate a test key pair
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("Failed to generate key pair: %v", err)
	}

	message := []byte("test message for canonical verification")

	// Create a signature - Go's ed25519.Sign may or may not produce strictly canonical
	signature := ed25519.Sign(privateKey, message)

	// First verify it's a valid signature
	if !ed25519.Verify(publicKey, message, signature) {
		t.Fatal("Base signature verification failed")
	}

	// Check if this particular signature is strictly canonical
	isStrictlyCanonical := IsCanonicalSignature(signature)

	// VerifyCanonical should accept if and only if the signature is strictly canonical
	result := VerifyCanonical(publicKey, message, signature)
	if result != isStrictlyCanonical {
		if isStrictlyCanonical {
			t.Error("VerifyCanonical() rejected a strictly canonical signature")
		} else {
			t.Error("VerifyCanonical() accepted a non-strictly-canonical signature")
		}
	}

	// If we got a non-canonical signature from Go, that's expected and we can skip
	// the rest of the canonical-specific tests
	if !isStrictlyCanonical {
		t.Skip("Go produced a non-strictly-canonical signature (S >= L/2), which is valid but not strictly canonical")
	}

	// Test with wrong message
	wrongMessage := []byte("wrong message")
	if VerifyCanonical(publicKey, wrongMessage, signature) {
		t.Error("VerifyCanonical() accepted signature for wrong message")
	}

	// Test with wrong public key
	wrongPublicKey, _, _ := ed25519.GenerateKey(rand.Reader)
	if VerifyCanonical(wrongPublicKey, message, signature) {
		t.Error("VerifyCanonical() accepted signature with wrong public key")
	}

	// Create a non-canonical signature for testing
	// Since Go's ed25519.Sign always produces canonical signatures,
	// we manually create a non-canonical one
	nonCanonicalSig := make([]byte, 64)
	copy(nonCanonicalSig[:32], signature[:32]) // Copy R component
	// Set S to halfL (non-canonical)
	copy(nonCanonicalSig[32:], halfL)

	if VerifyCanonical(publicKey, message, nonCanonicalSig) {
		t.Error("VerifyCanonical() accepted non-canonical signature")
	}
}

func TestCompareSignatures(t *testing.T) {
	sig1 := []byte("signature1signature1signature1signature1signature1signature1sig1")
	sig2 := []byte("signature1signature1signature1signature1signature1signature1sig1")
	sig3 := []byte("signature2signature2signature2signature2signature2signature2sig2")

	if !CompareSignatures(sig1, sig2) {
		t.Error("CompareSignatures() failed for equal signatures")
	}

	if CompareSignatures(sig1, sig3) {
		t.Error("CompareSignatures() returned true for different signatures")
	}

	if CompareSignatures(sig1, sig1[:32]) {
		t.Error("CompareSignatures() returned true for different lengths")
	}

	if CompareSignatures(nil, nil) {
		t.Error("CompareSignatures() should return false for nil inputs")
	}

	if CompareSignatures(nil, sig1) {
		t.Error("CompareSignatures() should return false when one input is nil")
	}

	if CompareSignatures(sig1, nil) {
		t.Error("CompareSignatures() should return false when one input is nil")
	}
}

func BenchmarkIsCanonicalSignature(b *testing.B) {
	sig := make([]byte, 64)
	rand.Read(sig)
	// Ensure it's canonical for consistent benchmark
	sig[63] = 0

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		IsCanonicalSignature(sig)
	}
}

func BenchmarkSign(b *testing.B) {
	_, privateKey, _ := ed25519.GenerateKey(rand.Reader)
	message := []byte("benchmark message")

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		Sign(privateKey, message)
	}
}

func TestHalfLConstantVerification(t *testing.T) {
	// Verify halfL constant against RFC 8032 specification
	// L = 2^252 + 27742317777372353535851937790883648493
	// L/2 = 2^251 + 13871158888686176767925968895441824246.5
	// In little-endian bytes, L/2 (rounded down) should be:
	expectedHalfL := []byte{
		0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58,
		0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08,
	}

	if !bytes.Equal(halfL, expectedHalfL) {
		t.Errorf("halfL constant is incorrect!")
		t.Errorf("Expected: %x", expectedHalfL)
		t.Errorf("Got:      %x", halfL)
		t.Fatal("CRITICAL SECURITY ERROR: halfL constant does not match RFC 8032 specification")
	}

	// Additional verification: test known boundary values
	// These are test vectors to ensure our constant is correct

	// Value exactly at L/2 should be non-canonical
	exactHalfL := make([]byte, 32)
	copy(exactHalfL, halfL)
	if isLessThanHalfL(exactHalfL) {
		t.Error("Value equal to halfL should not be less than halfL")
	}

	// Value at L/2 - 1 should be canonical
	halfLMinusOne := make([]byte, 32)
	copy(halfLMinusOne, halfL)
	// Subtract 1 from little-endian number
	for i := 0; i < 32; i++ {
		if halfLMinusOne[i] > 0 {
			halfLMinusOne[i]--
			break
		}
		halfLMinusOne[i] = 0xff
	}
	if !isLessThanHalfL(halfLMinusOne) {
		t.Error("Value at halfL-1 should be less than halfL (canonical)")
	}
}

func TestIsLessThanHalfL(t *testing.T) {
	tests := []struct {
		name string
		s    []byte
		want bool
	}{
		{
			name: "zero",
			s:    make([]byte, 32),
			want: true,
		},
		{
			name: "one",
			s: func() []byte {
				s := make([]byte, 32)
				s[0] = 1
				return s
			}(),
			want: true,
		},
		{
			name: "halfL_minus_one",
			s: func() []byte {
				s := make([]byte, 32)
				copy(s, halfL)
				s[0]-- // Subtract 1
				return s
			}(),
			want: true,
		},
		{
			name: "halfL_exact",
			s:    halfL,
			want: false,
		},
		{
			name: "halfL_plus_one",
			s: func() []byte {
				s := make([]byte, 32)
				copy(s, halfL)
				s[0]++ // Add 1
				return s
			}(),
			want: false,
		},
		{
			name: "max_value",
			s: func() []byte {
				s := make([]byte, 32)
				for i := range s {
					s[i] = 0xff
				}
				return s
			}(),
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isLessThanHalfL(tt.s)
			if got != tt.want {
				t.Errorf("isLessThanHalfL() = %v, want %v", got, tt.want)
				t.Logf("S:     %x", tt.s)
				t.Logf("halfL: %x", halfL)
			}
		})
	}
}
